Theme: jekyll-theme-minimal
Title: CV Teresa Lopes ✒️📄

Education:
10/01/2022- 03/03/2022
TechANTers
Damia Group Tech Recruitment Academy
Covers topics such as basic programming concepts, technical profiles, different types of businesses, recruitment processes and flows, CV screening, interviews, sourcing, announcements and personal branding in public platforms, negotiation and communication strategies and key essential skills for tech recruiters. 

03/09/2020-03/03/2022
CIPD Level 5 Diploma in Human Resources Management
ICS Learn
Includes topics such as resourcing, recruitment and selection, workforce, and talent planning, retaining talent, change management, performance reviews, leadership, labour market and trends, equality and diversity, motivation, reward, and employment law.

01/07/2019-01/01/2020
Professional Diploma in Leadership & Management
Shaw Academy, accredited by International Accreditation Organization, CPD certification Service and ICSOC
Incorporates subjects such as leadership, organizational culture, diversity management, innovation and creativity, communication, coaching, emotional intelligence, conflict management, strategic thinking, stress management, resilience, strategic awareness and change management.

24/09/2012-26/07/2016
Nursing Degree
Instituto Politécnico de Setúbal - Escola Superior de Saúde, Setúbal, Portugal
Comprises basic life support, basic pediatric life support and advanced life support, as well as modules in pediatrics, women and reproductive health, elderly care, psychiatry, complex and critical
care, and end of life care.

Work Experience:
01/02/2017-18/10/2021
Nurse
Broadmoor Hospital, High Secure Mental Health Hospital, Crowthorne, UK

01/08/2016-26/09/16
Nurse
High Secure Hospital São João de Deus, Mental Health Ward, Caxias- Lisbon, Portugal

Personal Statement:
My name is Teresa Lopes and I’m Portuguese. I’ve moved to the UK from sunny Portugal five years ago to pursue a better life. Up until now I was working as a nurse, however I needed a career change, so I decided to take my love for people and caring to the next level, by emerging myself in the world of people’s profession. I love working with people and that’s why I am so excited to start my career in the Human Resources area.
In my role as a nurse, I developed essential knowledge and skills transferable to my new area of interest, Human Resources, such as communication and relational skills, time management, teamwork, conflict resolution, performance reviews, leadership and even stress management.
Ive completed a diploma in Leadership & Management, which has provided me with an amazing insight into the relevance of appropriate management and leadership in the workplace; it has also provided me with the necessary skills to undertake a manager or leader role. I’m currently finishing the CIPD level 5 diploma in Human Resources Management, which has equipped me with amazing tools to be able to continue my work caring for people.
Im fluent in English, but also Portuguese and Spanish, and I’m presently working on my French! I’m enthusiastic and eager to learn, I’m quick on my feet, organized, resourceful, reliable, creative, a perfectionist (which sounds like a flaw, but it means I’ll always give my absolute best in any task), I’m very sociable and a great communicator… talking to people comes natural to me. I’m also not afraid to be original and unconventional!
I’m currently looking for a job in Tech recruitment!

Personal Skills:
Communication and relational skills, leadership skills, conflict resolution and stress management skills, organizational and managerial skills, and time management skills.
I also had the opportunity to complete relevant training in my practice as a nurse, which includes Therapeutic Boundaries, Cognitive Behavioral Therapy/ Dialectical Behavior Therapy, Motivational Interviewing, Stress Management and Conflict Resolution training.
Finally, I also possess a UK Driving License	B1, B. 

